import type { Metadata } from "next";
import { DM_Sans,Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${bricolageGrotesque.variable} antialiased`}
      >
        <div className="w-full mx-auto max-w-[1440px] h-full min-h-[1158px] px-[112px] pt-[48px] pb-[80px] bg-Neutral_900 ">
       <Navbar/>
        {children}
       </div>
      </body>
    </html>
  );
}
